### ISSUE TITLE
State of the game

### ISSUE THREAD

**Issue by snurby7** [snurby7/CloudFlocking#1]
Alright, so this is what I'm thinking on how to handle turns. We drop the state column. Plan and simple we won't need it. I'd suggest the following, we know that if a user created a game, they will have to play a round passing the baton to player one. This would mean the state would look like, 1 -> 2. We know that the order FLIPS every time, so once player 2 plays in the end of Round 1, the order is 2 -> 1. This cycle would repeat until we have a collision or invalid placement. So the rounds for each and EVERY game would go | 1 -> 2 |  | 2 -> 1|  |1 -> 2| and so on. This would make us really not need a game state field. We could instead change the STATE column to maybe a previous round followed by a complete column, which gets set on invalid input, so we'd just send a message to the server saying, it's over (show the user they lost and the other they won and remove the game). Reply to this issue with your thoughts, just so that way we can keep our issues in one area.

**Comment by folksjos** [comment]
Alright, I see exactly where you are going with this solution. I agree with
what you are saying that we do not need a state column and we can use the
turn column or something to keep the reversing order turn. So the complete
column would in the end return a message to the server which is then sent
to the winner player saying that the game is over? This makes sense and
could definitely work. The final score really only needs to be stored in
the game itself.

Also, another question. I noticed in the changes of the app you mentioned
JSON, how much do you know about JSON and what would be use it for? Im not
too familiar with it, but I can learn.

Thanks for everything you did!


Highest Regards,

Joshua Folks
Computer Engineering
College of Engineering
Michigan State University
folksjos@msu.edu
313.433.8944

**Comment by snurby7** [comment]
I know next to nothing about JSON, I wasn't sure if that could be easier to send and receive, just thought I'd leave it as a possibility. You've pretty much got my thought, we just send a message to the server if a user fails, and in the polling we check quick to see if the game over column (whatever it's named)  is not empty. If it is, that player stored in the column is the winner. Shouldn't be too hard to implement, maybe a status=complete winner=X or something.

**Comment by folksjos** [comment]
Oh ok yea I was just making sure on that JSON. I can read up on it to see if it's easier. Yea that sounds like a good plan I can do that. Have we thought about what we are going to do about the timing? Like if the connection is lost or the user doesn't respond for a number of seconds?
